using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExampleApplication.Models
{
    public class Course
    {
        //The DatabaseGenerated attribute with the None parameter on the CourseID
        //proterty specifies that primary key values are provided by the user 
        //rather tan generated by the database. 
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }

        [Range(0,5)]
        public int Credits { get; set; }

        public int DepartmentID { get; set; }

         public Department Department { get; set; }

        //A course can have any number of students enrolled in it,
        //so the Enrollments navigation property is a collection.
        public ICollection<Enrollment> Enrollements { get; set; }
        public ICollection<CourseAssignment> CourseAssignments { get; set; }
    }
}
